default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wren_development
  username: violet
  password: <%= ENV['WREN_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: wren_test

production:
  <<: *default
  database: wren_production
  username: violet
  password: <%= ENV['WREN_DATABASE_PASSWORD'] %>
